# Gradle properties
org.gradle.java.home=C:/Program Files/Android/Android Studio1/jbr
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false

# Android build properties
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.builtInKotlin=false
android.newDsl=false

# Suppress legacy AGP DSL warnings
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL
